from app.models.carrera_materia import CarreraMateria
from app.models.carrera import Carreras
from app.models.categorias import Categorias
from app.models.estudiante_carrera import EstudiantesCarreras
from app.models.estudiante_logro import EstudianteLogros
from app.models.estudiante_materia import EstudianteMateria
from app.models.estudiante import Estudiantes
from app.models.logro_materia import LogroMaterias
from app.models.logro import Logros
from app.models.materia import Materias